### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sparks3875392**
A suggestion for more readme notes to clarify how set up with HACS and the Home Assistant OS GUI. The process is different as the GUI doesn't like resource files being added to the ui files directly.

### CODE REVIEW

**Comment by twrecked** [comment]
Thanks for doing this, I know I've fallen behind with the documentation. My only comment is I think you need to add a newline before `type: 'custom:aarlo-glance'` in the example card.

**Comment by sparks3875392** [comment]
OK, that's great. Let me take some time to clean this up properly and I'll submit a new commit. 
Thanks for a brilliant integration.

**Comment by sparks3875392** [comment]
Sorry for delay and my neophyte skills. Hopefully this is ok and will help others like me who are new to this.

**Comment by twrecked** [comment]
No worries. Thanks for the help!

**Pull request merged**
